version: '2'

services:
# Uncomment when running Behat.
#   selenium:
#     image: selenium/standalone-chrome
  db-mysql:
    #image: mysql:5.5
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: {{ cookiecutter.db_root_pass }}
      MYSQL_DATABASE: {{ cookiecutter.db_name }}
      MYSQL_USER: {{ cookiecutter.db_user }}
      MYSQL_PASSWORD: {{ cookiecutter.db_pass }}
    ports:
      - "3306:3306"
  webserver:
    #image: jobyh/moodle-php:php5.6-apache
    image: jobyh/moodle-php:php7.1-apache
    depends_on:
      - db-mysql
    volumes:
      - ./html:/var/www/html
      - ./data:/var/www/data
    ports:
      - "80:80"
    restart: always
    environment:
      - OPCACHE_ENABLE_CLI=0
#      - XDEBUG_CONFIG="idekey=PHPSTORM remote_enable=1 remote_port=9000 remote_host=192.168.56.1 remote_connect_back=1"
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"  # web interface
      - "1025:1025"  # SMTP port: set $CFG->smtphosts='mailcatcher:1025';
volumes:
  db_data:
